endpoints/urls.py
from django.conf.urls import patterns, url, include
from django.views.generic import TemplateView
from django.contrib import admin
from .views import start_periodic_reporting, kickoff_periodic_scans

admin.autodiscover()

urlpatterns = patterns(
    "",
    url(r'^admin/', include(admin.site.urls)),
    url(r"^$", "endpoints.views.list_test_results"),
    url(r"^dashboard/$", "endpoints.views.list_test_results"),
    url(r"^dashboard/(?P<page2return2>\d{1,2})/$", "endpoints.views.list_test_results"),
    url(r"^testDetails/(?P<result_id>\d{1,11})/(?P<page2return2>\d{1,2})/$", "endpoints.views.test_result_details"),
    url(r"^deleteTestResultDetails$", "endpoints.views.delete_test_result_details"),
    url(r"^settings$", "endpoints.views.configure"),
    url(r"^addURL$", "endpoints.views.add_url"),
    # --- change URL details ---
    #url(r"^getChangeURLDetails$", "endpoints.views.get_change_url_details"),
    url(r"^changeURLDetails$", "endpoints.views.change_url_details"),
    url(r"^deleteURLDetails$", "endpoints.views.delete_url_details"),
    url(r"^searchURL/?$", "endpoints.views.search_url"),
    url(r"^summaryReport$", "endpoints.views.summary_report"),
    url(r"^certReport$", "endpoints.views.cert_report"),
    # --- contact ---
    url(r"^addContact/?$", "endpoints.views.add_contact"),
    url(r"^getChangeContact$", "endpoints.views.get_change_contact"),
    url(r"^changeContact/?$", "endpoints.views.change_contact"),
    url(r"^updateContact/?$", "endpoints.views.update_contact"),
    url(r"^searchContact/?$", "endpoints.views.search_contact"),
    url(r"^deleteContact/?$", "endpoints.views.delete_contact"),
    # --- product ---
    url(r"^searchProduct/?$", "endpoints.views.search_product"),
    url(r"^addProduct$", "endpoints.views.add_product"),
    url(r"^changeProduct$", "endpoints.views.change_product"),
    url(r"^updateProduct$", "endpoints.views.update_product"),
    url(r"^productSummary$", "endpoints.views.product_overview"),
    url(r"^product/(?P<product_id>[0-9]+)/$", "endpoints.views.product_results"),
    # --- misc ---
    #url(r"^deleteURL/?$", "endpoints.views.delete_url"),
    url(r"^submitForScan$", "endpoints.views.submit_for_scan"),
    #url(r"^purgeOldTests$", "endpoints.views.purge_old_tests"),
    #url(r"^sendEmailToContact/?$", "endpoints.views.send_email_to_contact"),
    # --- login ---
    url(r'^login$', 'django.contrib.auth.views.login',
        {'template_name': 'login.html'}, name='login'),
    url(r"^logout/?$", "endpoints.views.logout"),
    url(r"^init/?$", "endpoints.views.init_threads"),
)

urls.py
from django.conf.urls import patterns, url, include
#from django.views.generic import TemplateView
from django.contrib import admin

admin.autodiscover()

urlpatterns = patterns(
    "",
    url(r'^admin/', include(admin.site.urls)),
    url(r"^endpoints/", include("TLSManager.endpoints.urls")),
)

endpoints/models.py
from django.db import models

# Create your models here.
class Contact(models.Model):
    first_name = models.CharField(max_length=128)
    last_name = models.CharField(max_length=128)
    email = models.EmailField()
    def __unicode__(self):
        return "Contact: %s %s (%s)" % (self.first_name, self.last_name, self.email)

class Defect(models.Model):
    description = models.CharField(max_length=256)
    def __unicode__(self):
        return self.description

class Product(models.Model):
    name = models.CharField(max_length=256)
    contacts = models.ManyToManyField(Contact)
    def __unicode__(self):
        return "Product: %s" % (self.name)

class TestResult(models.Model):
    time = models.DateTimeField()
    ip_address = models.CharField(max_length=256)
    score = models.CharField(max_length=16)
    defects = models.ManyToManyField(Defect)
    the_endpoint = models.ForeignKey("Endpoint")
    def __unicode__(self):
        return "Test Result: Score(%s);Time(%s)" % (self.score, self.time)


class Endpoint(models.Model):
    url = models.URLField()
    test_results = models.ManyToManyField(TestResult)
    product = models.ForeignKey(Product)
    expiry_date = models.DateField(null=True,default=None)
    def __unicode__(self):
        return "Endpoint: %s" % (self.url)

class Setting(models.Model):
    default_email = models.EmailField(default='security.engineering@rackspace.com')
    scan_enabled = models.BooleanField(default=False)
    default_scan_frequency = models.IntegerField(default=1)
    scan_score_threshold = models.CharField(max_length=16)
    auto_purge = models.BooleanField(default=False)
    test_retention_period = models.IntegerField(default=1)

endpoints/forms.py
from django import forms
from .models import Contact, Product

#class EmailForm(forms.Form):
#	name = forms.CharField(required=False)
#	email = forms.EmailField()

class ProductForm(forms.ModelForm):
	class Meta:
		model = Product

class ContactForm(forms.ModelForm):
	class Meta:
		model = Contact

endpoints/views.py
from django.template import loader, Context
from django.template import RequestContext
from django.core.paginator import Paginator
from django.core.mail import send_mail
from django.core.context_processors import csrf
from django.shortcuts import render_to_response
from django.shortcuts import get_object_or_404
from django.db import connection
from django.db.models import Q
from django.db.models import Max
from django.http import HttpResponse, HttpResponseRedirect
from django.http import Http404
from django.utils import timezone
from django.contrib import auth
from django.contrib.auth.decorators import login_required
from django.conf import settings
from .models import Contact, Product, Endpoint, TestResult, Defect, Setting
from errno import ECONNREFUSED
import logging
import requests
import simplejson
import threading
import multiprocessing
from subprocess import Popen, PIPE, STDOUT
import datetime
import OpenSSL
import socket
import random
import pickle
import pytz
import time
import sys
import ast
import os
import parse_ssllabs

logger = logging.getLogger(__name__)
lines_per_page = 15


def list_test_results(request, page2return2='0'):
    errors = []
    page_data = {}
    page_direction = 'Next'
    current_page = '0'
    endpoint_tr_tuples = []
    current_sort_order = 'url'

    check_good_number(page2return2)
    if page2return2 != '0':
        current_page = str(int(page2return2) - 1)

    if request.method == 'POST':
        if not request.POST.get('page_to_display', ''):
            current_page = '0'
        else:
            check_good_number(request.POST['page_to_display'])
            current_page = request.POST['page_to_display']

        if not request.POST.get('page_direction', ''):
            page_direction = 'Next'
        else:
            check_valid_size(request.POST['page_direction'])
            page_direction = request.POST['page_direction']

        if not request.POST.get('current_sort_order', ''):
            current_sort_order = 'url'
        else:
            check_valid_size(request.POST['current_sort_order'])
            current_sort_order = request.POST['current_sort_order']

        if request.POST.get('url', ''):  # url sort button pressed
            current_sort_order = 'url'
            page_direction = 'Next'
            current_page = '0'
            endpoints_all = Endpoint.objects.all().order_by('url')
            endpoint_tr_tuples = create_endpoint_last_tr_tuples(endpoints_all)
        elif request.POST.get('product', ''):  # product sort button pressed
            current_sort_order = 'product'
            page_direction = 'Next'
            current_page = '0'
            endpoints_all = Endpoint.objects.all().order_by('product__name')
            endpoint_tr_tuples = create_endpoint_last_tr_tuples(endpoints_all)
        elif request.POST.get('last_scan_date', ''):  # last_scan_date sort
            current_sort_order = 'last_scan_date'
            page_direction = 'Next'
            current_page = '0'
            endpoints_all = Endpoint.objects.all().order_by('product__name')
            endpoint_tr_tuples = create_endpoint_last_tr_tuples(endpoints_all)
            endpoint_tr_tuples = sort_by_time(endpoint_tr_tuples)
        elif request.POST.get('score', ''):  # score sort button pressed
            current_sort_order = 'score'
            page_direction = 'Next'
            current_page = '0'
            endpoints_all = Endpoint.objects.all().order_by('product__name')
            endpoint_tr_tuples = create_endpoint_last_tr_tuples(endpoints_all)
            endpoint_tr_tuples = sort_by_score(endpoint_tr_tuples)
        else:  # Next or Prev button cases
            endpoint_tr_tuples = create_tuple_set_for_sort_order(
                                                            current_sort_order)
    else:  # method GET
        endpoints_all = Endpoint.objects.all().order_by('url')
        #endpoint_tr_tuples = create_endpoint_last_tr_tuples(endpoints_all)
        # if coming from a Return from the details page
        if 'current_sort_order' in request.COOKIES:
            current_sort_order = request.COOKIES['current_sort_order']
        endpoint_tr_tuples = create_tuple_set_for_sort_order(
                                                            current_sort_order)

    endpoint_tr_tuple_page = paginate_list(endpoint_tr_tuples,
                                           page_data,
                                           current_page,
                                           page_direction)

    page_data['errors'] = errors
    page_data['endpoint_tr_tuples'] = endpoint_tr_tuple_page
    page_data['current_sort_order'] = current_sort_order

    response = render_to_response('test_results.html',
                                  page_data, RequestContext(request))
    response.set_cookie('current_sort_order', current_sort_order)
    return response


def create_tuple_set_for_sort_order(current_sort_order):
    if current_sort_order == 'url':
        endpoints_all = Endpoint.objects.all().order_by('url')
        endpoint_tr_tuples = create_endpoint_last_tr_tuples(endpoints_all)
    elif current_sort_order == 'product':
        endpoints_all = Endpoint.objects.all().order_by('product__name')
        endpoint_tr_tuples = create_endpoint_last_tr_tuples(endpoints_all)
    elif current_sort_order == 'last_scan_date':
        endpoints_all = Endpoint.objects.all().order_by('product__name')
        endpoint_tr_tuples = create_endpoint_last_tr_tuples(endpoints_all)
        endpoint_tr_tuples = sort_by_time(endpoint_tr_tuples)
    elif current_sort_order == 'score':
        endpoints_all = Endpoint.objects.all().order_by('product__name')
        endpoint_tr_tuples = create_endpoint_last_tr_tuples(endpoints_all)
        endpoint_tr_tuples = sort_by_score(endpoint_tr_tuples)
    else:
        endpoints_all = Endpoint.objects.all().order_by('url')
        endpoint_tr_tuples = create_endpoint_last_tr_tuples(endpoints_all)
    return endpoint_tr_tuples


# endpoint_tr_tuples is a list of tuples
# each tuple is composed of an endpoint, its last test result
# and the next to last test result.
def create_endpoint_last_tr_tuples(endpoints_all):
    timezone.activate(pytz.timezone('America/Chicago'))

    endpoint_tr_tuples = []
    for endpoint in endpoints_all:
        tr_lst = endpoint.test_results.all().order_by('-time')  # don't change
        if len(tr_lst) > 1:
            endpoint_tr_tuples.append((endpoint, tr_lst[0], tr_lst[1]))
            #logger.info('=== endpoint=' + str(endpoint.url))
            #logger.info('-------------')
        elif len(tr_lst) > 0:
            endpoint_tr_tuples.append((endpoint, tr_lst[0], None))
        else:
            endpoint_tr_tuples.append((endpoint, None, None))
    return endpoint_tr_tuples


# endpoint_tr_tuples is a list of tuples
# each tuple is composed of an endpoint, its last test result
# and the next to last test result. This function sort by the test result time
def sort_by_time(endpoint_tr_tuples):
    utc = pytz.utc
    epoch_time = datetime.datetime(1970, 1, 1, 0, 0, 0, 0, tzinfo=utc)
    endpoint_tr_tuples.sort(key=lambda tup:
                            (epoch_time if tup[1] is None else tup[1].time))
    endpoint_tr_tuples.reverse()
    return endpoint_tr_tuples


# endpoint_tr_tuples is a list of tuples
# each tuple is composed of an endpoint, its last test result
# and the next to last test result. This function sort by the test result score
def sort_by_score(endpoint_tr_tuples):
    sorted_by_second = sorted(endpoint_tr_tuples, key=lambda tup:
                              ('' if tup[1] is None else tup[1].score))
    sorted_by_second.reverse()
    return sorted_by_second


def paginate_list(list_to_paginate, page_data, current_page, page_direction):
    p = Paginator(list_to_paginate, lines_per_page)
    page_2_display = p.page(1)
    page_data['first_page'] = None
    page_data['last_page'] = None
    if current_page == '0':  # first time displaying search result
        if p.page(1).count > 0:  # there are rows to display
            page_2_display = p.page(1)
            page_data['page_to_display'] = 1
    else:
        if page_direction == 'Next':
            if p.page(int(current_page)).has_next():
                next_page_number = p.page(
                    int(current_page)).next_page_number()
                page_2_display = p.page(next_page_number)
                page_data['page_to_display'] = next_page_number
        else:
            if p.page(int(current_page)).has_previous():
                prev_page_number = p.page(
                    int(current_page)).previous_page_number()
                page_2_display = p.page(prev_page_number)
                page_data['page_to_display'] = prev_page_number

    if p.num_pages == 1:  # only a single page of rows so do not display arrows
        page_data['first_page'] = page_data['last_page'] = True
    else:
        if not page_2_display.has_previous():
            page_data['first_page'] = True
        else:
            page_data['first_page'] = False
        if not page_2_display.has_next():
            page_data['last_page'] = True
        else:
            page_data['last_page'] = False

    list_page = page_2_display.object_list
    return list_page


def product_results(request, product_id):
    check_good_number(product_id)
    page_data = {}
    last_endpoint_result = Endpoint.objects.annotate(Max('testresult__id')) \
        .filter(product_id=product_id, testresult__id__max__isnull=False) \
        .values('testresult__id__max')
    endpoint_results = Endpoint.objects.filter(testresult__id__in=last_endpoint_result) \
        .values('url', 'id', 'testresult__id', 'testresult__score', 'testresult__time')
    page_data['endpoint_results'] = endpoint_results
    return render_to_response('product_results.html', page_data, RequestContext(request))


def tab(request):
    page_data = {}

endpoints/templates/add_product.html
{% extends 'base.html' %}

{% block content %}

    <div class="form-horizontal">

        <form method='POST' action='' style="max-width: 90%" class="form-add-product" >
            <h2 class="form-add-product-heading">Enter Product Details</h2>

    {% csrf_token %}
    {% if errors %}
        <ul>
            {% for error in errors %}
            <li><p class="text-danger">{{ error }}</p></li>
            {% endfor %}
        </ul>
    {% endif %}

            <br/>

                <div class="form-group">
                    <label class="col-sm-2 control-label"
                               for="id_name">Product Name</label>
                    <div class="col-sm-10  ">
                        <input class="form-control" id="id_name" maxlength="60" name="name" type="text" value="{{name}}"/>
                    </div>
                </div>
            
            <br/>

                <div class="form-group">
                    <label class="col-sm-2 control-label"
                               for="id_contacts">Contacts</label>
                    <div class="col-sm-10">
                        <select class="form-control" id="id_contacts" name="contacts">
                            {% for contact in contacts %}
                                <option value="{{ contact.id }}">{{ contact.email }}</option>
                            {% endfor %}
                        </select>
                    </div>
                </div>
            
            <br/>
            
                <div class="form-group">
                    <div class="col-sm-offset-2 col-sm-10">
                        <input type='submit' value='Add Product' class='btn btn-primary' />
                    </div>
                </div>
        
        </form>

    </div>


{% endblock %}

endpoints/templates/add_url.html
{% extends 'base.html' %}

{% block content %}

    <div class="form-horizontal">

      <form class="form-add-url" style="max-width: 90%" action="addURL" method="POST">
        <h2 class="form-add-url-heading">Enter URL Details</h2>

    {% csrf_token %}
    {% if errors %}
        <ul>
            {% for error in errors %}
            <li>{{ error }}</li>
            {% endfor %}
        </ul>
    {% endif %}

            <br/>

        <div class="form-group">
            <label class="col-sm-2 control-label"
                       for="id_url">URL</label>
            <div class="col-sm-10  ">
                <input class="form-control" id="id_url"  cols="100" maxlength="100" name="url" type="text" />
            </div>
        </div>

            <br/>

        <div class="form-group">
            <label class="col-sm-2 control-label"
                       for="id_prod_manager">Product&nbsp;Name</label>
            <!-- div class="col-sm-10  ">
                <input class="form-control" id="id_prod_name"  cols="100" maxlength="100" name="product_name" type="text" />
            </div -->
            <div class="col-sm-10">
                <select class="form-control" id="id_product" name="products">
                    {% for product in products %}
                        <option value="{{ product.id }}">{{ product.name }}</option>
                    {% endfor %}
                </select>
            </div>
        </div>

            <!-- br/>

        <div class="form-group">
            <label class="col-sm-2 control-label"
                       for="id_prod_manager">Contact&nbsp;Email</label>
            <div class="col-sm-10  ">
                <input class="form-control" id="id_email"  cols="40" maxlength="30" name="email" type="text" />
            </div>
        </div -->

            <br/>

        <div class="form-group">
                <label class="col-sm-2 control-label"
                       for="id_frequency">Check&nbsp;Frequency</label>
            <div class="col-sm-10">
                <select class="form-control" id="id_frequency" name="check_frequency">
                  <option value="1">Daily</option>
                  <option value="2">Every 2 days</option>
                  <option value="3">Weekly</option>
                  <option value="4">Monthly</option>
                  <option value="5">Quarterly</option>
                  <option value="6">Yearly</option>
                </select>
            </div>
        </div>

            <br/>


        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <input class="btn btn-primary" type="submit" value="Add URL"/>
            </div>
        </div>

      </form>

    </div> <!-- /container -->

{% endblock %}

endpoints/templates/purge_tests.html
{% extends 'base.html' %}

{% block content %}

    <div class="form-horizontal">

        <form method='POST' action='' style="max-width: 90%" class="form-purge-tests" >
            <h2 class="form-purge-tests-heading">Enter Purge Criteria</h2>

    {% csrf_token %}
    {% if errors %}
        <ul>
            {% for error in errors %}
            <li><p class="text-danger">{{ error }}</p></li>
            {% endfor %}
        </ul>
    {% endif %}

            <br/>

                <div class="form-group">
                    <label class="col-sm-2 control-label"
                               for="id_name">Older than</label>
                    <div class="col-sm-10  ">
                        <select class="form-control" id="id_product" name="product">
                                <option value="1">1 Week</option>
                                <option value="1">1 Month</option>
                                <option value="1">1 Quarter</option>
                                <option value="1">6 Months</option>
                                <option value="1">1 Year</option>
                                <option value="1">2 Years</option>
                        </select>
                    </div>
                </div>
            
            <br/>

                <div class="form-group">
                    <label class="col-sm-2 control-label"
                               for="id_contacts">Product Name</label>
                    <div class="col-sm-10">
                        <select class="form-control" id="id_product" name="product">
                            {% for product in products %}
                                <option value="{{ product.id }}">{{ product.name }}</option>
                            {% endfor %}
                        </select>
                    </div>
                </div>

            <br/>

        <div class="form-group">
                <label class="col-sm-2 control-label"
                       for="id_prod_type">Purge Score Threshold:</label>
            <div class="col-sm-10">
                <select class="form-control" id="id_score" name="scan_score_threshold">
                <option value="A" {% ifequal config.scan_score_threshold 'A' %}selected="selected"{% endifequal %}>A</option>
                <option value="A-" {% ifequal config.scan_score_threshold 'A-' %}selected="selected"{% endifequal %}>A-</option>
                <option value="B" {% ifequal config.scan_score_threshold 'B' %}selected="selected"{% endifequal %}>B</option>
                <option value="C" {% ifequal config.scan_score_threshold 'C' %}selected="selected"{% endifequal %}>C</option>
                <option value="M" {% ifequal config.scan_score_threshold 'M' %}selected="selected"{% endifequal %}>M</option>
                <option value="N" {% ifequal config.scan_score_threshold 'N' %}selected="selected"{% endifequal %}>N</option>
                <option value="F" {% ifequal config.scan_score_threshold 'F' %}selected="selected"{% endifequal %}>F</option>
                </select>
            </div>
        </div>

            <br/>
            
                <div class="form-group">
                    <div class="col-sm-offset-2 col-sm-10">
                        <input type='submit' value='Purge' class='btn btn-primary' />
                    </div>
                </div>
        
        </form>

    </div>


{% endblock %}

endpoints/templates/test_details.html
{% extends 'base.html' %}

{% block content %}

<div class="form-horizontal">

  <form class="form-add-url" style="max-width: 90%">
    <h2 class="form-add-url-heading">Test Details</h2>

    {% csrf_token %}
    {% if errors %}
        <ul>
            {% for error in errors %}
            <li><p class="text-danger">{{ error }}</p></li>
            {% endfor %}
        </ul>
    {% endif %}
    
        <br/>

    <div class="form-group">
        <label class="col-sm-2 control-label"
                   for="id_prod_manager">URL</label>
        <div class="col-sm-10   form-control-static">{{result.the_endpoint.url}}
        </div>
    </div>

    <div class="form-group">
        <label class="col-sm-2 control-label"
                   for="id_prod_manager">Last&nbsp;Scan&nbsp;Date</label>
        <div class="col-sm-10   form-control-static">{{result.time}}
        </div>
    </div>

    <div class="form-group">
        <label class="col-sm-2 control-label"
                   for="id_score">Last&nbsp;Score</label>
        <div class="col-sm-10   form-control-static">{{result.score}}
        </div>
    </div>

    <div class="form-group">
        <label class="col-sm-2 control-label"
                   for="id_defects">Defects</label>
        <div class="col-sm-10   form-control-static">
            <table>
			{% for defect in defects %}
			<tr><td>{{defect.description}}</td></tr>
			{% endfor %}
			</table>
        </div>
    </div>

    <div class="form-group">
        <label class="col-sm-2 control-label"
                   for="id_prod_name">Product&nbsp;Name</label>
        <div class="col-sm-10   form-control-static">{{product.name}}
        </div>
    </div>

    <div class="form-group">
        <label class="col-sm-2 control-label"
                   for="id_prod_email">Product&nbsp;Contact</label>
        <div class="col-sm-10   form-control-static">{{contact.email}}
        </div>
    </div>

    <div class="form-group">
        <label class="col-sm-2 control-label"
                   for="id_prod_email">Previous&nbsp;Scans</label>
        <div class="col-sm-10  form-control-static">
  <div class="row" style="max-width: 95%">
      <div class="panel panel-default" style="max-height: 100px; overflow:auto">
        <table class="table table-fixed table-striped">
          <tbody>
          {% for res in hist_results %}
            <tr>
              <td class="col-xs-6" style="padding: 3px 4px 3px 13px;">{{res.time}}</td><td class="col-xs-3" style="padding: 3px 4px 3px 7px;">Score: {{res.score}}</td><td class="col-xs-3" style="padding: 3px 4px 3px 7px;"></td>
            </tr>
          {% endfor %}
          </tbody>
        </table>
      </div>
  </div>
        </div>
    </div>


    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <input class="btn btn-primary" type="button" name="return" value="Return" onclick="returnToResultsList({{result.id}}, {{page2return2}});"/>&nbsp;&nbsp;&nbsp;&nbsp;
            <input class="btn btn-primary" type="button" onclick="submitForScan('{{result.the_endpoint.id}}');" name="{{result.the_endpoint.id}}" value="Re-Scan"/>
            {% if user.is_authenticated %}
            <input class="btn btn-primary" type="button" name="delete" value="Delete" data-href="/deleteTestResultDetails?result_id={{result.id}}" data-toggle="modal" data-target="#confirm-delete"/>&nbsp;&nbsp;&nbsp;&nbsp;
            <input class="btn btn-primary" type="button" name="email" value="Send Email to Contact" onclick="sendEmail({{result.id}});"/>
            {% endif %}
        </div>
    </div>


  
<div class="modal fade" id="confirm-delete" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h5 class="modal-title" id="myModalLabel">Confirm Delete</h5>
            </div>
            <div class="modal-body">
                <h4>Are you sure you want to delete this test result?</h4>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                <a class="btn btn-danger btn-ok">Delete</a>
            </div>
        </div>
    </div>
</div>  
  </form>

</div> <!-- /container -->

{% endblock %}

endpoints/templates/test_details_fake.html
{% extends 'base.html' %}

{% block content %}

    <div class="form-horizontal">

      <form class="form-add-url" style="max-width: 90%">
        <h2 class="form-add-url-heading">Test Details</h2>
        
            <div class="form-group">
            <label class="col-sm-2 control-label"
                       for="xxxxx">&nbsp;</label>
            </div>

        <div class="form-group">
            <label class="col-sm-2 control-label"
                       for="id_prod_manager">URL</label>
            <div class="col-sm-10  ">
                <input class="form-control" id="id_url"  cols="40" maxlength="30" name="url" type="text" value="https://www.rackspace.com"/>
            </div>
        </div>

            <div class="control-group"></div>

        <div class="form-group">
            <label class="col-sm-2 control-label"
                       for="id_prod_manager">Scan Date</label>
            <div class="col-sm-10  ">
                <input class="form-control" id="id_scan_date"  cols="40" maxlength="30" name="scan_date" type="text" value="Apr 15, 2015 10:45AM"/>
            </div>
        </div>

            <div class="control-group"></div>

        <div class="form-group">
            <label class="col-sm-2 control-label"
                       for="id_prod_manager">Score</label>
            <div class="col-sm-10  ">
                <input class="form-control" id="id_score"  cols="40" maxlength="30" name="score" type="text" value="B"/>
            </div>
        </div>

            <div class="control-group"></div>

        <div class="form-group">
            <label class="col-sm-2 control-label"
                       for="id_prod_manager">Flaws</label>
            <div class="col-sm-10  ">
                <input class="form-control" id="id_flaws"  cols="40" maxlength="30" name="flaws" type="text" value="Poodle, RC4"/>
            </div>
        </div>

            <div class="control-group"></div>

        <div class="form-group">
            <label class="col-sm-2 control-label"
                       for="id_prod_manager">Product&nbsp;Name</label>
            <div class="col-sm-10  ">
                <input class="form-control" id="id_prod_name"  cols="40" maxlength="30" name="product_name" type="text" value="Reach"/>
            </div>
        </div>

            <div class="control-group"></div>

        <div class="form-group">
            <label class="col-sm-2 control-label"
                       for="id_prod_manager">Contact&nbsp;Email</label>
            <div class="col-sm-10  ">
                <input class="form-control" id="id_email"  cols="40" maxlength="30" name="email" type="text" value="security.engineering@rackspace.com"/>
            </div>
        </div>

            <div class="control-group"></div>

        <div class="form-group">
                <label class="col-sm-2 control-label"
                       for="id_prod_type">Check&nbsp;Frequency</label>
            <div class="col-sm-10">
                <input class="form-control" id="id_frequency"  cols="40" maxlength="30" name="email" type="text" value="Daily"/>
            </div>
        </div>

            <div class="form-group">
            <label class="col-sm-2 control-label"
                       for="xxxxx">&nbsp;</label>
            </div>


        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <input class="btn btn-primary" type="submit" value="Return" onclick="window.location.href=dashboard"/>
            </div>
        </div>

      </form>

    </div> <!-- /container -->

{% endblock %}